# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='name')),
                ('opens_at', models.TimeField(verbose_name='opens at')),
                ('closes_at', models.TimeField(verbose_name='closes at')),
                ('_notes', models.CharField(default=None, max_length=100, null=True, verbose_name='_notes')),
            ],
        ),
    ]
